default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: site_development
test:
  <<: *default
  database: site_test

production:
  <<: *default
  database: site_production
  username: site
  password: <%= ENV['SITE_DATABASE_PASSWORD'] %>
